apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  # annotations:
  # dev.okteto.com/generate-host: backend-ingress
spec:
  rules:
    - host: k8s.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi-back-service
                port:
                  number: 80
