apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  # https://www.okteto.com/docs/cloud/ssl
  annotations:
    dev.okteto.com/generate-host: backend-ingress
spec:
  rules:
    - host: backend-pr-2-megaredhand.cloud.okteto.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi-back-service
                port:
                  number: 80
