name: "Create preview"

# file: .github/workflows/preview.yaml
on:
  push:
    branches: [ main ]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Deploy
        uses: okteto/pipeline@latest
        with:
          name: example-megaredhand
          timeout: 15m
