name: "CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: make install
      - name: Run linter
        run: make lint
      - name: Run MyPy
        run: make mypy
      - name: Run tests
        run: make test
